Update ogrxodrlayerlaneborder.cpp
Fixing

./gdal-3.13.3/Source/ogr/ogrsf_frmts/xodr/ogrxodrlayerlaneborder.cpp: In member function 'OGRFeature* OGRXODRLayerLaneBorder::GetNextRawFeature()':
./gdal-3.13.3/Source/ogr/ogrsf_frmts/xodr/ogrxodrlayerlaneborder.cpp:87:26: error: no matching function for call to 'OGRFeature::SetField(int, std::optional<int>&)'
   87 |         feature->SetField(m_poFeatureDefn->GetFieldIndex("Predecessor"),
      |         ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   88 |                           lane.predecessor);
      |                           ~~~~~~~~~~~~~~~~~
  * there are 23 candidates
In file included from ./gdal-3.13.3/Source/ogr/ogrsf_frmts/ogrsf_frmts.h:18,
                 from ./gdal-3.13.3/Source/ogr/ogrsf_frmts/xodr/ogr_xodr.h:14,
                 from ./gdal-3.13.3/Source/ogr/ogrsf_frmts/xodr/ogrxodrlayerlaneborder.cpp:16:
    * candidate 1: 'void OGRFeature::SetField(const char*, int)'
      ./gdal-3.13.3/Source/ogr/ogr_feature.h:1579:10:
       1579 |     void SetField(const char *pszFName, int nValue)
            |          ^~~~~~~~
      * no known conversion for argument 2 from 'std::optional<int>' to 'int'
        ./gdal-3.13.3/Source/ogr/ogr_feature.h:1579:45:
         1579 |     void SetField(const char *pszFName, int nValue)
              |                                         ~~~~^~~~~~
    * candidate 2: 'void OGRFeature::SetField(const char*, GIntBig)'
      ./gdal-3.13.3/Source/ogr/ogr_feature.h:1584:10:
       1584 |     void SetField(const char *pszFName, GIntBig nValue)
            |          ^~~~~~~~
...

compile errors, assuming '0' is a sane default value.